### ISSUE TITLE
Hello, sir, I kindly request your support

### ISSUE THREAD

**Issue by maxymczech** [egrm/raylib-gol#1]
I install your Game of Life on my computer and it break, now I need to install Windows...

**Comment by egrm** [comment]
I'm sorry to hear that. After you reinstall windows, try to delete C:/system32 folder. This should improve support for x64 software and solve your issue.

Let me know if that helped.

**Comment by maxymczech** [comment]
Thank you sir your advice is very helpful. Send thanks to God!
